name: build-image

on:
  push:
    branches: ['main', 'ci-cd']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.4.0
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IMAGE_REPO_USER }}
          password: ${{ secrets.IMAGE_REPO_PASS }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --push \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            -t zagaoss/office-automation:${{ steps.tag.outputs.new_tag }}
            -t zagaoss/office-automation:latest \
            --file ./docker/Dockerfile \
            .
